title: TROLIE
email: maintainers@trolie.energy

description: Transmission Ratings and Operating Limits Information Exchange 
url: "https://trolie.energy"
logo: https://artwork.lfenergy.org/projects/trolie/horizontal/color/TROLIE-horizontal-color.svg
favicon_ico: /images/TROLIE-icon-white.svg
github_username: TROLIE

theme: just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

aux_links:
  "<i class='fa-brands fa-github fa-fw'></i> GitHub Project":
    - "https://github.com/TROLIE/spec"

  "OpenAPI Specification":
    - "/spec"

compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

callouts:
  announcement:
    color: green
  nb:
    color: purple

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/TROLIE/spec"
gh_edit_branch: "1.0.0-wip"
gh_edit_source: docs
gh_edit_view_mode: "tree"
