title: TROLIE
email: your-email@example.com

description: >-
 Transmission Ratings and Operating Limits Information Exchange 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://trolie.energy" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: TROLIE

# Build settings
remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-remote-theme
